### ISSUE TITLE
What about -Ofast?

### ISSUE THREAD

**Issue by funghetto** [InBetweenNames/gentooLTO#106]
What is your experience with it? 
Are there some packages that can benefit from it and how many packages will break with it?

**Comment by InBetweenNames** [comment]
I believe @preney built his system with `-Ofast` and ended up reverting. It's to be expected, since `-Ofast` makes assumptions counter to how IEEE-754 arithmetic actually works. I think on a per-package basis it's reasonable, but I wouldn't recommend it globally, nor would I consider it a bug if it didn't behave well with a particular package. As for how many packages will break, I have no idea. I do use it on my OpenWRT firmware without any issues, but that's a fairly restricted subset of packages, many of which likely don't even use floating point.

**Comment by mleise** [comment]
Trouble is it wont fall apart during compilation or linking, but yields subtly different results in FP math code that violate the C specification and can go unnoticed for a while until some program input hits an edge case. It is a recipe to introduce your own [heisenbugs](https://en.wikipedia.org/wiki/Heisenbug) into working foreign code.
