### ISSUE TITLE
STRIP_MASK is banned in EAPI7

### ISSUE THREAD

**Issue by juippis** [InBetweenNames/gentooLTO#119]
Lately Ive had some troubles emerging EAPI7 ebuilds with STRIP_MASK="*.a"

This seems to be related, 
https://bugs.gentoo.org/203891#c59

Ive just disabled strip_mask for now. Wanted to get this info out here to see if anyone had tips about this.

**Comment by InBetweenNames** [comment]
Thanks very much for the info -- we'll definitely need to change how we prevent stripping of static archives with EAPI 7. According to the [linked commit](https://gitweb.gentoo.org/proj/pms.git/commit/?id=373ec493c322530b72f7bafb7db846a522704184) , it looks like STRIP_MASK is still the way to go for EAPIs < 7, and it's just ignored for EAPI 7.

It appears that the exclusion is performed on a per-package basis. Hopefully I can find something in here that allows for a global exclusion for static archives. Granted, if the GNU strip utility behaved nicely with LTO, this wouldn't be a problem at all...

**Comment by InBetweenNames** [comment]
Looking at the document here:

https://projects.gentoo.org/pms/7/pms.pdf#subsection.12.3.11

It appears the `RESTRICT` variable can be set to somewhat recover the old behaviour. It appears that it would apply to all files rather than just static archives, which is unfortunate, because we really only need `*.a` to be left as-is.

I'm going to look into what can be done about this in the next couple of days.  If fixing GNU `strip` is easy, then I'll just put a modified ebuild here for that.  Otherwise I'll have to look at some kind of kludge.  

In the meantime, you can keep `STRIP_MASK` as it was, since it's still perfectly valid for old EAPIs, and EAPI 7 just ignores it.

**Comment by InBetweenNames** [comment]
Reference #49

**Comment by InBetweenNames** [comment]
The LTO symbol mangling bug may be fixed in binutils 2.30.x. I'll give it a more extensive test later.

**Comment by InBetweenNames** [comment]
I rebuilt zlib and parts of Qt without any STRIP_MASK applied on binutils 2.30. So far things look good. I'll do a full system rebuild to verify.

**Comment by InBetweenNames** [comment]
Okay, not out of the woods with just removing STRIP_MASK. I'll start investigating a patch to binutils to fix this proper.

**Comment by InBetweenNames** [comment]
A portage patch was added to `master` to address this.
