### ISSUE TITLE
thunderbird dont like lto with gcc or clang 

### ISSUE THREAD

**Issue by javashin** [InBetweenNames/gentooLTO#273]
the ebuild log is too big cant paste here after disable lto is compilling with CFLAGS="-O3 -march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -ftree-loop-distribution -falign-functions=32 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -pipe"

ERROR: 
cargo-linker error: undefined symbol: rust_libloading_dlerror_mutex_unlock
using rust-bin

with ld.gold or

 ld.lld: error: undefined symbol: rust_libloading_dlerror_mutex_unlock

**Comment by javashin** [comment]
any ideas ?

**Comment by javashin** [comment]
Ok I Got It Now Its rust-bin the problem i need it because i only have 4G of Ram and i Cant Compile rust which needs 8g of ram .. can someone confirm this happen when using rust-bin on a "ltoized" gentoo
like ours . thanks in advance for now no lto and gpo for firefox or thunderbird .

**Comment by ElDavoo** [comment]
I use normal rust and thunderbird with gentoolto, no problems (apart from the apocalyptic compilation time, a pain every time there is an update).
Try:
1)Minimize your used ram: use a text console and not X, put swappiness to 100, run openrc in interactive mode to disable unnecessary init services
2)In make.conf, set makeopts to -j1, also nthreads=1.
3)Build rust emerging with I_KNOW_WHAT_I_AM_DOING=1

**Comment by ionenwks** [comment]
> for now no lto and gpo for firefox or thunderbird

I don't know anything about thunderbird and haven't messed with rust much, but a note for firefox... When using the `lto` USE flag, it auto-detects how many cores/threads you have and will automatically use `-flto=<cores>` which (for me) results in `=12`. Since I also use tmpfs for building, I run out of memory during linking even with my 16GB depending on toolchain used. But it's fine if I lower it to `-flto=6` (in your case and if have over 2 cores, you "may" need to force it to use `-flto=2` or maybe 1, along with `-j1` and some healthy amount of swap in case, if you also use pgo, I imagine it may take 24+ hours to build.. good luck).

As to how to force it.. I'm honestly not sure what's the best way, trying to pass `-flto` flag to firefox yourself tend to result in disaster, so I just used a user patch instead (it's a dirty patch that just directly change it, edit as needed).
[firefox-lto-count.zip](https://github.com/InBetweenNames/gentooLTO/files/3052131/firefox-lto-count.zip)

May also want to omit `-pipe`, using temporary files instead of pipes should result in a bit less memory usage.

**Comment by ElDavoo** [comment]
strangely i'm now having this issue too

**Comment by ElDavoo** [comment]
I can't compile with -ffat-lto-objects because the linker runs out of RAM, but looks like it goes past the previous failure point.
thunderbird without LTO at all compiles fine.

**Comment by ElDavoo** [comment]
but has segmentation fault as soon as I open an email...

**Comment by barolo** [comment]
> but has segmentation fault as soon as I open an email...

gcc or clang?

**Comment by ElDavoo** [comment]
gcc 8.3.0
