### ISSUE TITLE
dont compile re2 and re2c with lto 

### ISSUE THREAD

**Issue by javashin** [InBetweenNames/gentooLTO#278]
llvm-strip: error: '/var/tmp/portage/dev-libs/re2-0.2019.03.01/image/usr/lib/libre2.a': The file was not recognized as a valid object file
   /usr/lib64/libre2.a
llvm-strip: error: '/var/tmp/portage/dev-libs/re2-0.2019.03.01/image/usr/lib64/libre2.a': The file was not recognized as a valid object file
   /usr/lib64/libre2.so.gentoo-2019-03-01.0.0
 that is with clang and with gcc its worst

**Comment by gcs-github** [comment]
re2 and re2c compile fine on my systems with
`CFLAGS="-O3 -pipe -march=haswell -flto=8 -fuse-linker-plugin -fipa-pta -fgraphite-identity -floop-nest-optimize -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu"`

Your re2-0.2019-03.01 also doesn't seem to come from the main gentoo ebuild tree, since that version is not in there yet: https://github.com/gentoo/gentoo/tree/master/dev-libs/re2

Can you
1. Check that compiling re2 with the same CFLAGS/CXXFLAGS as the ones I gave you and under GCC 8.3.0-r1 works? (that would indicate this is not an LTO problem)
2. Can you check whether you can compile `dev-libs/re2::gentoo` with and without switching to my CFLAGS/CXXFLAGS (in which case it might indicate a problem with the ebuild/version from the overlay you got it from)

**Comment by InBetweenNames** [comment]
I can't reproduce this either.  It looks like you're using `llvm-strip` though... how does that interact with GCC object files?  Is there a reason you aren't using GNU strip?

**Comment by javashin** [comment]
to compile chromium re2 needs to be recompiled with clang the chromium ebuild from pg_overlay forces to use clang and if re2 is compiled with lto with gcc or clang gives , but if llvm-strip is used its give you The file was not recognized as a valid object file with gnu-strip dont say anyrhing but the chromium build fails because its not sane the *.a file please try to reproduce this compiling chromium from pg_overlay which have the last version plus patched with vaapi for video hardware acceleration also jasonpp needs to be recompiled with clang in order to compile chromium too its a bit hacky this chromium ........
