### ISSUE TITLE
Fix the travis config to pull in the mv overlay

### ISSUE THREAD

**Issue by InBetweenNames** [InBetweenNames/gentooLTO#28]
As this overlay now depends on the mv overlay, we'll have to amend the CI tests to pull in that overlay as well

**Comment by mgomersbach** [comment]
We currently just copy the overlay in /usr/local/portage and a piece of local storage in travis (the repo)
This is not very compatible with multiple overlays.

Preferably I'd use layman. It does it cleanly and concisely.

One of the problems I have with layman is dependency:
This [bug](https://bugs.gentoo.org/545568)  , has someone working on it [here](https://github.com/gentoo/layman/compare/master...Hummer12007:recursive) and [here](https://github.com/gentoo/layman/pull/40)

The other is development workflow:
When a repository is listed in the global overlay list, it is IMPOSSIBLE to supply another upstream resource.
The repository from the global list always takes precedence because the URL's from the command-line option are APPENDED. So forks will never be able to use CI.

Sadly the development on layman staggers a bit because they seem to stay compatible with Gentoo derivatives.
Understandable but we need to creative til then...

**Comment by InBetweenNames** [comment]
I wish I knew more about docker and Travis!  I wonder if it may be possible to directly write a "repos.conf" file that contains the "mv" overlay?  For example:

~~~
[mv]
location = /usr/local/mv
sync-type = git
sync-uri = https://anongit.gentoo.org/git/user/mv.git
auto-sync = Yes
~~~

As long as that's done before the `emerge --sync`, it should be automatically pulled in and populated.  Is that possible to do?

**Comment by mgomersbach** [comment]
That might be an idea.
Coincidentally; if we just use that ebuild, should we include the entire overlay of mv?

**Comment by InBetweenNames** [comment]
If we could pull in just the ebuild that actually might work.  Although the `layout.conf` might make repoman complain since it does list the `mv` dependency in there.  Worth a shot I think!

**Comment by darkbasic** [comment]
Can't you just run `layman -a mv` inside the docker container?

**Comment by mgomersbach** [comment]
Yes we can, but should we?
That is one extensive overlay and would like to keep this clean.

**Comment by InBetweenNames** [comment]
I've pushed up a hack to get it to work for now.  When we come up with a better solution we can replace this with it.

**Comment by InBetweenNames** [comment]
Argh.  I'm just going to comment it out until we figure it out.  Unfortunately I can't spend any more time on it today.

**Comment by darkbasic** [comment]
> I've pushed up a hack to get it to work for now.

This is basically the portage equivalent of a `layman -a mv`.

> Yes we can, but should we?
That is one extensive overlay and would like to keep this clean.

We need to filter out the other ebuilds, because we don't want to pollute our CI system with packages coming from other overlays. At the same time we always want latest version of `portage-bashrc-mv`, so we can't simply add a static ebuild to our docker image.
This is a problem even in our own system, because most of the times we simply want a couple of ebuilds from an overlay, while we want to keep using the portage version for everything else.
The solution could be to mask the whole overlay and unmask the packages we need.

`/etc/portage/package.mask`:
```
*/*::mv
```

`/etc/portage/package.unmask`:
```
app-portage/portage-bashrc-mv::mv
```

The only issue is that if we already have some entries in `/etc/portage/package.unmask` they will also unmask the corresponding package from the overlay. So we need to either use `app-something/package-name::gentoo` when unmasking packages or, in alternative, we need to **hard** mask the overlay.

**Comment by InBetweenNames** [comment]
I ended up pulling in the MV overlay directly with a shallow clone.  It's not perfect but it works, and I like low maintenance.  However I'd like to revisit the idea of only pulling in the directories we need from the MV overlay.  Currently, we add the `mv` overlay into `repos.conf` and then do an `emerge --sync`, pulling it all in.  It would be ideal to do a [Sparse Checkout](https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository/13738951#13738951) of only what we need.  I would happily accept a PR for that.  I'll leave this issue open for further discussion on that.

**Comment by darkbasic** [comment]
Sparse checkout could be a solution indeed, but in the meantime we should still mask `*/*::mv` and unmask just `app-portage/portage-bashrc-mv::mv` to avoid polluting the global scope. If we don't we may end up with failing tests or false positives because of the overlay.

**Comment by mgomersbach** [comment]
What is the point of working on this if we are hell bent on making it a big mess.

**Comment by darkbasic** [comment]
> if we are hell bent on making it a big mess

Why should we?

**Comment by InBetweenNames** [comment]
I'll happily accept a PR for any improvements to the CI :) However I have to be clear on this: my position is that we have CI right now and it works.  It's not a mission critical component and it can be removed if for some reason it breaks down the line, without time pressure on getting a fix out.  As better ways of doing it come along, we can adopt those.  From what I can tell, there is no "right" way of doing it with overlays.

**Comment by darkbasic** [comment]
> From what I can tell, there is no "right" way of doing it with overlays.

That's for sure, in my opinion Gentoo really needs to better handle namespaces.

**Comment by InBetweenNames** [comment]
Agreed.  What we're really doing here is working around weaknesses in Portage.  I only chose the solution I did because it was the least intrusive and the least amount of work.  However as everyone in this thread has seen, if there are better or accepted solutions, I am more than happy to incorporate/migrate to those instead.

**Comment by mgomersbach** [comment]
Sure, there is no "ONE RIGHT" way of doing things. But there are many wrong ways.
I gave a fairly clean solution that was tested and works.
It provided something to work from.
It is always harder to repair than prevent and apparently my advice/experience/testing is worth less than "oooooh shiny, no idea what it does, but lets add it"

**Comment by darkbasic** [comment]
Why do you take it so personally?
@InBetweenNames clearly stated that he wanted to avoid the hassle of manually updating the ebuild, which means that every other solution (sparse checkout, mask/unmask...) is completely fine for him if someone wants to make a PR.
By the way I still didn't understand why you don't like my approach of masking the whole overlay and unmasking only the package we need. I did use such method for years and I have never had any namespace override, can you please enlighten me with your experience? Maybe I do miss something?

**Comment by mgomersbach** [comment]
I don't take it personally. It is just very demotivating to put a lot of time and effort into something clean, whilst upstream prefers the duct tape approach. Do you think others can still use mv overlay in conjunction with ours? Nope. Mv himself? Nope. Etc.
Look this is not my repo and everybody is free to do whatever they want but I can say that I prefer not to work that way without 'taking it personally'

**Comment by InBetweenNames** [comment]
@mgomersbach , I have both the MV overlay and this overlay installed on my system at the same time and it works perfectly fine.  Was that not the case on yours?

**Comment by mgomersbach** [comment]
Yes. Using that masking unmasking approach makes the use of mv overlay nasty. Especially when someone else actually uses that overlay. But if someone tried it: you'd know. That's is exactly where my frustration lies. I love the good suggestions, but they are incorporated without testing in stark contrast to what I try to do. I promised a clean stream of PR's and instead the amount I need to correct or remove is increases for no good reason. So like I said. There is no one good way and there are many bad ones. Maybe I should just return to this repo when everybody has tried their own suggestion and learned their lesson.

**Comment by darkbasic** [comment]
> Do you think others can still use mv overlay in conjunction with ours? Nope. Mv himself? Nope. Etc.

> Yes. Using that masking unmasking approach makes the use of mv overlay nasty. Especially when someone else actually uses that overlay.

Are we talking about the CI or what else? Because if we're talking about CI then **only** the docker image needs to do the mask/unmask trick and nobody else does. Users will still need to emerge `portage-bashrc-mv` the way they prefer (adding the `mv` overlay, copy-pasting the ebuild, adding the `mv` overlay and masking/unmasking it, etc).

My proposed solution was for the CI **only**.

If you seek for a way to provide `portage-bashrc-mv` to the users then this is the approach I would take: there are bots which closely follow upstream and automatically make PRs when whatever they were watching for changed. Such a way you could still embed the ebuild without the hassle of manually updating it.

**Comment by InBetweenNames** [comment]
@mgomersbach I didn't actually incorporate any masking here, because I am undecided about how to "cherry pick" things from other overlays.  I brought the entire thing in only to the testing suite because, well, that's how it's expected to be used (see README.md).  Note that repoman is only checking the validity of this overlay, not MV.  If you have a better way of doing that, I'm all ears.

About your PR: I'm not a fan of taking ebuilds from other repos and slightly modifying them, introducing potential breaking changes to users of the "real" ebuilds.  I don't plan on maintaining the MV overlay stuff separately, and lets be honest: you don't want to deal with that either.  In addition to this, I have not been able to find any instances of overlays pulling in ebuilds from other overlays and slightly modifying them for testing purposes, so in the absence of precedent that means that my own value judgment is all I have to go on.  Unfortunately, as the owner and maintainer of this overlay, that means I have to be the bad guy sometimes and make a judgment call.

While I highly value your contributions, I have to be up front with you and say your comments attacking the character of other contributors here are unwelcome.  Well, to be clear, you can call me every name in the book for all I care, but I have to draw the line when it gets directed towards other people.  I created this discussion thread to try to converge on a good solution.  That means that unfortunately not all solutions will be accepted.  If you look, this applies to my solutions too just as it applies to everyone else's: I've changed my mind about many things since starting this project, realizing there are better solutions out there than what I had originally.  In the end, it's just code, and you are not your code!

Fortunately for you, this overlay isn't a job.  No one's asking you to do anything--you don't have a boss and you certainly don't have a deadline.  That means that before putting in a bunch of work into something, you can create issue threads to talk about it first and see how best to go about what you want to have in the overlay.  Also in your favour is that I'm a patient person willing to sift through big PRs that don't merge cleanly with HEAD, because I see value in every contribution and although I might not merge everything, I will at least probably merge something from it.  I understand what it's like to be in your position, where upstream isn't accepting changes that are "obviously" the way to go.  However I'm hearing you out and I do want to see a "real" solution to this down the line.  Your feedback in any issue thread always helps steer the discussion, even if your own solution doesn't get accepted.  There's big value in that.

**Comment by mgomersbach** [comment]
I am sorry if anyone felt attacked. Obviously that is not my intention. But please show me were I attacked so I can prevent that next time.

For one I do have seen the pulling of ebuilds a lot. It is far from ideal, but to my opinion less convoluted than pulling an entire repo (please don't be insulted by me saying that)

Also that ebuild is not for just testing purposes. It is to be delivering functionality that we had in the previous in the form of env/package.env. That was not the chosen path, fair, then I promise to rebase it around that ebuild, but instead of trying that we "try all the things" (please don't be insulted)

I don't think you are a bad guy. I never stated that. Maybe less informed or experienced (please don't be insulted)

It is cool that you state "you are not your code". I feel differently. I don't want my name on something that does the opposite of what I want my name under? Does that make me a bad guy?

Like I said before. I will not contribute to this specific repo. Not out of anger. Not out of resentment. But out of experience. If somebody does not want to listen to good advice, means they like to find out themselves. That's perfectly fine. And that's exactly what is going to happen here. There is nothing wrong with that right? Nobody needs to feel attacked by my decision for others to start contributing (and learning, undoing and eventually finding out that the first tested suggestion is actually what you are going for)

I wish you NOTHING BUT THE BEST. (but without me for a while)

**Comment by InBetweenNames** [comment]
@mgomersbach I respect your intentions and I wish you the best in the ventures that you pursue in the future.  I hope that someday you will decide to come back!

Addressing your question about "attacking":

> It is always harder to repair than prevent and apparently my advice/experience/testing is worth less than "oooooh shiny, no idea what it does, but lets add it"

So the implication here is that we have no attention span and we're attracted to "new" or "shiny" objects.  Also, we're inexperienced and incompetent.  We should just listen to you, because you obviously know better.  That's a bit demeaning, don't you think?

In general your tone seems to imply that if someone disagrees with you, they are wrong by default due to your experience.  You rely heavily on your experience to provide merit to your arguments, but you provide no background on what that might actually be.  I've got no idea who you are!  Your GitHub is pretty sparse, and I even tried going to the website linked on your profile but it didn't seem to be related to you.  Maybe you're John Carmack for all I know.  So if you want to point me to your resume, or LinkedIn, or CV, then that could actually help you here.  Even so, an argument from logic is strictly better than one from authority.

>It is cool that you state "you are not your code". I feel differently. I don't want my name on something that does the opposite of what I want my name under? Does that make me a bad guy?

Absolutely not.  The problem is you're going to get into situations like these, which lead to a lot of anger, resentment and ultimately time wasted, for naught.  Criticism will be taken personally, a reject on a PR is a rejection on you as a person, if your code sucks then you suck, and so on... In the corporate world it's basically impossible to do that and stay sane.  I mean, just look at how this thread has devolved, and we didn't even have money or time on the line.  Lets look at what happened:  I questioned your approach at doing things, you got angry, and now you're leaving the project.  That's okay with me, but ask yourself: did it really have to go that way?  Was there anything you could have done differently?  Don't answer it now, think about it in a year or two after this happens a few more times.

Here's my advice to you for next time:

* When you want to contribute to an open source project, talk to the maintainers before putting a lot of time into a patch.  Maybe start an issue or a forum post first.

* Don't expect your opinions to be taken as being more important than others by default.  At least qualify them with something.

* Try not to take criticism on proposed solutions so personally.

* Chunk out your PRs into smaller ones that merge cleanly with HEAD.

Since this thread has now been completely derailed, I'm closing it.

**Comment by mgomersbach** [comment]
Ah yes, you are right. Thank you. It seems different for me earlier.
This repo is actually the first non-professional public project I decided to work heavily on.
I will take your advice, specifically about the assumed prestige of myself.

However, can't relate to the assumption that I feel attacked.
Taking a step back and watch for a while just seems like the logical choice for me.

**Comment by darkbasic** [comment]
> I am sorry if anyone felt attacked.

Feeling attacked is not the main problem for me, I have a great experience dealing with guys full of themselves (I'm not talking about you know) and I learned to not ever take things personally, or at least not caring too much when the consequences do not concern me directly.
What makes me sad is seeing the same pattern again and again: great contributors leaving good projects for no real reason except misunderstandings.
Your behaviour will damage yourself more than anyone else, because you will feel attacked while nobody else is willing to (I speak mainly for myself, but I'm ready to put my hand on fire that @InBetweenNames didn't want to attack you in any way).
Seriously, I do not even use Gentoo anymore since a couple of years and the only reason I'm here is because I recognize the value in this project and I want to keep it alive. I have no interest in seeing my PR accepted because I don't even have the means to test it at the moment (I use a different distro).
I contribute in the only way I can: sharing my ideas but especially keeping the technical debate alive, because every project is going to stagnate with no interest.
Poisoning the general mood with personal attacks is not going to help, because it will turn away contributors, even if the ones towards the attack is directed can withstand it.
I don't care if you attack me, but if sharing my ideas indirectly contributes toward poisoning everyone else's mood then I'm not going to share them anymore, because it will do more harm than good. This kind of behaviour once again leads to stagnation.
Please be friends and do ourselves a favour: le's stop taking things so seriously. Everyone will gain from this, including this project which just lost a great contributor for no reason.
