### ISSUE TITLE
Enabling -fno-plt

### ISSUE THREAD

**Issue by nivedita76** [InBetweenNames/gentooLTO#302]
@ionenwks thanks for the heads up about `-fno-plt`

_Originally posted by @InBetweenNames in https://github.com/InBetweenNames/gentooLTO/issues/184#issuecomment-438697729_

**Comment by nivedita76** [comment]
Just creating a separate issue to track this. I have built world (kde-plasma with ~1375 packages) with -fno-plt for everything except x11-base/xorg-server and x11-drivers/* -- the ebuilds for these use -z lazy and no-plt breaks lazy binding. No build failures and everything seems to be working.

**Comment by ionenwks** [comment]
Yeah, generally only issues I had were with lazy bindings and "some" 32-bit version of packages for some reason as I mentioned in the previous issue (notably with 32-bit nss, ffmpeg, and pcsx2 -- the last one can't be built 64-bit, so...). Lazy bindings already don't get used much anymore for security reasons, at best it's a minor gain on program startup but then a minor loss can happen during run time.

For the more adventurous, glibc built with no-plt (flagomatic blocked) does fail some tests, but it's all regarding lazy bindings and I don't think it affects anything (including xorg).

Haven't really tracked the status of this in linkers, but reminder it "could" be minor performance loss in some cases if not using gold linker (then again, the issue may not be present when LTO is used).

**Comment by nivedita76** [comment]
I tested with a little sample and bfd seems to change the indirect call into direct as well (for functions in same shared object)

**Comment by ionenwks** [comment]
Nice, one less thing to worry about then. Can't really think of a lot of reasons to not use `-fno-plt` at this point.

**Comment by nivedita76** [comment]
Something's wrong with my gcc-9.1.0, just took a look at the -dumpspecs and the -z now is missing (I'm on hardened). Trying to figure it out.

**Comment by nivedita76** [comment]
Hm its there now after rebuild

**Comment by ionenwks** [comment]
> Yeah, generally only issues I had were with lazy bindings and "some" 32-bit version of packages

On a side-reminder (if anyone still get the same issues on 32-bit), gentoo does provide a usable `CFLAGS_x86` and `CFLAGS_amd64` env var which I used on those packages, if don't want to disable it for the more-used 64-bit version but let the 32-bit build normally.

**Comment by nivedita76** [comment]
For the 32-bit packages were those build errors? I've enabled both 32 and 64-bit ABIs and I didn't get any build problems at least.

**Comment by ionenwks** [comment]
> For the 32-bit packages were those build errors? I've enabled both 32 and 64-bit ABIs and I didn't get any build problems at least.

Been a while since I messed with that really (few months), so issues might have been resolved with newer gcc/packages (I haven't installed gcc 9 yet, still on 8.3, was leaving for later).

Don't have my older logs but tried again just now with 8.3 and gold anyway with a simple `-march=native -O2 -fno-plt`. ffmpeg seems fine now (can't remember what kind of errors it was formely giving), dev-libs/nss failed due to a `shlibsign` segfault (works if I omit no-plt on nss, shlibsign wasn't even built with it and normally works so I'm not sure what's up with that, would need more digging).

As for pcsx2, there's no 64-bit version to compare if one works and the other don't, but it fails immediately only with `-fno-plt` while testing for dependencies (pcsx2's cflags beyond `-fno-plt` were specified by pcsx2 itself).
`/usr/bin/x86_64-pc-linux-gnu-gcc  -m32 -march=native -O2 -fno-plt  -fno-PIE  -pipe -fvisibility=hidden -pthread -fno-builtin-strcmp -fno-builtin-memcmp -mfpmath=sse -Wall -Wextra -Wno-attributes -Wno-unused-function -Wno-unused-parameter -Wno-missing-field-initializers  -Wno-unused-value  -Wstrict-aliasing -Wstrict-overflow=1   -DNDEBUG   -fuse-linker-plugin -flto=12 -DCHECK_FUNCTION_EXISTS=IceConnectionNumber  -Wl,-O1 -Wl,--as-needed  -rdynamic CMakeFiles/cmTC_e3ffd.dir/CheckFunctionExists.c.o  -o cmTC_e3ffd -lICE 
/tmp/portage/games-emulation/pcsx2-9999/temp/ccSd6BZU.ltrans0.ltrans.o:<artificial>:function main: error: unexpected reloc 43 against global symbol IceConnectionNumber without base register in object file when generating a position-independent output file
collect2: error: ld returned 1 exit status`

**Comment by ionenwks** [comment]
^ In PCSX2's case, I'm guessing it's related to xorg (ICE library) and just more lazy bindings issues. So this is really only dev-libs/nss that's being strange right now.

**Comment by InBetweenNames** [comment]
I'll be doing a full system rebuild with `-fno-plt` soon!  After that, I'll likely include it in the default config.  I have to do a bit of a refactor of `sys-config/ltoize` first to make things more manageable.

**Comment by InBetweenNames** [comment]
Just curious, what benefits of lazy binding are we missing out on by using `-fno-plt`?

**Comment by ionenwks** [comment]
I'm no expert on the topic but lazy bindings very slightly help with startup times, especially for applications using a ridiculous amount of shared libraries like KDE. And lazy bindings simply don't work with `-fno-plt`, in a way it kinda implies `-z now` which some people already use along with relro for security reasons.

But then you'll gain on performance at run time instead. From a very basic tests, I've found no-plt to help a decent amount if calling shared library functions at a high rate in a loop. I guess using one or the other can depend on your priorities, I know some are looking at startup times more than anything else.

**Comment by javashin** [comment]
im using this flag too i hope it improves startup times jeje , glibc compiled fine with it and ipa too so slowly im getting to the new standard here IPA+PLT

**Comment by nivedita76** [comment]
@javashin to be clear, -fno-plt will increase startup times a little, IF you were previously using lazy binding, which I think is the default unless you're using hardened, or the ebuild/library explicitly enables it -- for eg gentoo's ebuild always builds glibc with bind-now so the C library itself is not going to become slower.

**Comment by javashin** [comment]
hmm i just changed to no pie and no ssp and compiling gcc now with noplt

**Comment by javashin** [comment]
gcc with
EXTRA_ECONF='--with-build-config=bootstrap-lto'
USE=pgo
BOOT_CFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fipa-pta -fno-plt -fno-stack-protector"



CFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fno-stack-protector -pipe"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"
CPPFLAGS="${CFLAGS}"

**Comment by javashin** [comment]
@nivedita76 using -falign-functions=32 -falign-loops=32 -falign-jumps=32 never compiled here how you get that to work ?? always error error

**Comment by javashin** [comment]
also im eliminating -falign-loops=32 -falign-jumps=32 from my cflags glibc compiled with those fine but mesa dont work OK with them i got artifacts and glitches for some reason i have a intel gfx hd 4600 haswell

**Comment by javashin** [comment]
if that is for mesa imagine other software

**Comment by javashin** [comment]
we have to choose wisely what we use for *FLAGS There is a line between Fast/stable we need balance not add all the cflags out there just for "AMOR AL ARTE" without getting any optimization at all but instead just getting breakage ......

**Comment by nivedita76** [comment]
The alignment flags have never caused an issue for me. I really don’t see how they can be a problem as all they do is cause nops to be inserted if needed.

**Comment by ionenwks** [comment]
> @javashin to be clear, -fno-plt will increase startup times a little, IF you were previously using lazy binding

or at least in theory, on applications with fewer shared libraries but aggressively use their functions at start up, maybe it could be faster.. maybe

**Comment by nivedita76** [comment]
Also note I use bfd linker rather than gold, though I think both should be compatible. I was thinking a couple months back about switching to gold but then saw this and left it alone

https://www.phoronix.com/scan.php?page=news_item&px=GNU-Gold-Stagnate-F31

**Comment by InBetweenNames** [comment]
Just did a full system rebuild with `-fno-plt` to try it out.  I'll give it a whirl for a week or two and see how it goes.  Note that gold did much better that bfd for many programs in the rebuild -- I am strongly considering making it default via `-fuse-ld=gold`.  Also, I added our first `-fno-plt` workaround!

One thing I'd like to investigate is to see how prelink is doing these days.  Since lazy binding doesn't work with `-fno-plt`, it seems that it would make a lot of sense to use prelinked ELF binaries to help avoid the startup overhead.  Does anyone have experience with prelink in modern Gentoo systems?  I'm getting married this weekend so I won't have much time to mess around with it.  But if it's a supported thing, I'd like to try it out.

**Comment by nivedita76** [comment]
@InBetweenNames if you try it out note that with 17.0 pie is turned on in gcc, you'll have to remove it and rebuild world without PIE.

**Comment by javashin** [comment]
ffmpeg is not ok with noplt failed here

**Comment by InBetweenNames** [comment]
@nivedita76 thanks for the heads up!  It seems it's set in `toolchain.eclass`, and therefore even takes precedence over `make.conf`.  Ouch!

**Comment by nivedita76** [comment]
> @nivedita76 thanks for the heads up! It seems it's set in `toolchain.eclass`, and therefore even takes precedence over `make.conf`. Ouch!

It's a use flag so you can turn it off. But you need to override use.force from the profile using package.use.force I think? But I saw later that you do have a no-PIE build -- how did you do that?

**Comment by InBetweenNames** [comment]
I think I actually was wrong about being no-PIE, as all I did was have `USE=-pie nopie` in `make.conf`.  I thought that would have been sufficient to disable PIE on my system.  I didn't realize that `package.use.force` was necessary to truly disable it.  I see now that `USE=pie` for gcc doesn't just support making PIE executables, it makes them the default.  I'll be doing a world rebuild again soon enough!

**Comment by javashin** [comment]
@InBetweenNames check out https://github.com/InBetweenNames/gentooLTO/issues/261

**Comment by ionenwks** [comment]
When in doubt, just run `file` on your executables, they will be called shared objects (with PIE) instead of an executable. Not using PIE does lead to a few separate issues here and there, mostly a side-effect of every major distributions using it and nothing being tested without it anymore (despite the optimization focus, I've read even Clear Linux is planning to start using it soon if not already). I used to have a no-PIE system myself but I switched back.

**Comment by javashin** [comment]
im using this system with no pie and no ssp and is working fine and gcc dont make pie executable anymore 
i think even audacious-plugins was compiling without -fPIC

**Comment by InBetweenNames** [comment]
@javashin @ionenwks thank you!  I'm learning new things all the time on here.  Trying out the patch in that thread as we speak.  It looks like the difference between position dependent and independent is pretty marginal on x86-64, but I still think we should have the freedom to choose.  In fact, it sounds like it would make for a great wiki entry!
