### ISSUE TITLE
dev-lang/python hangs when using -Ofast

### ISSUE THREAD

**Issue by glitchking007** [InBetweenNames/gentooLTO#326]
python-3.7.3 hangs during emerge when compiling test_buffers.py with -Ofast

**Comment by javashin** [comment]
-Ofast is not supported yet i think but good to know that python dont like it what about 2.7 and 3.6 ?

**Comment by glitchking007** [comment]
I Just tried emerging python 3.6.8 and the same issue arises. With python 2.7.16 the issue isn't present.
I worked around the issue by adding
`# BEGIN: Workaround -Ofast Issues
dev-lang/python /-Ofast/-O3 # Causes /Lib/test/test_buffers.py to hang
# END: Workaround -Ofast Issues`
to ltoworkarounds.conf

**Comment by InBetweenNames** [comment]
I think it's a reasonable workaround, as `-Ofast` users would likely want to use `-O3` as the second best choice and `-O3` and lower users would be unaffected.

**Comment by ionenwks** [comment]
While I'd believe most would want `-O3`, for the sake of still not forcing which -O* to replace it with, could instead add `-fno-fast-math` (or whichever thing is causing the problem) as a workaround. In general I feel this would be better for any -O* workarounds as well if can narrow down the problem.

**Comment by InBetweenNames** [comment]
Yeah that's a better idea, actually.  There are only a couple of possibilities really.

**Comment by asaparov** [comment]
@glitchking007 Were you able to emerge dev-lang/python-2.7.15-r108 by replacing `-Ofast` with `-O3` for that package only, without disabling any additional tests beyond those in the ebuild? Is the rest of your system also built with `-Ofast`? (such as `glibc`, `sandbox`, `ncurses`, `readline`, `bzip2`, `zlib`, `openssl`)

**Comment by glitchking007** [comment]
I haven't tried any other versions other then the ones specified above I can check it when I have time. I am currently trying to get my entire system compiled with -Ofast but I am running into a plethora of issues with the assortment of Cflags I am using.

**Comment by asaparov** [comment]
Ah got it. So on my machines, I've noticed that as long as any of the dynamic library dependencies of python are compiled with `-funsafe-math-optimizations`, then emerging python will fail during testing at any optimization level (the emerge makes python run a bunch of self-correctness tests after compiling). This is due to the fact that `-funsafe-math-optimizations` changes floating point arithmetic behavior such that even when libraries are loaded dynamically, the unsafe floating point behavior is passed onto python (more specifically, the MXCSR register is changed by the dynamic libraries and kept while python runs). This then causes the math tests to fail. See: https://github.com/uclouvain/openjpeg/issues/488 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55522

So adding the per-package flag `-fno-fast-math` to python will allow it to compile for `-Ofast` users, but the emerge will still fail during the test phase.

I mention this in an earlier issue: https://github.com/InBetweenNames/gentooLTO/issues/200
There, I found that the specific flag causing the compilation issues was `-ffinite-math-only`.

One solution would be to:
1. Add the flag `-fno-finite-math-only`,
2. If the flag `-funsafe-math-optimizations` is enabled (either directly or via `-Ofast` or `-ffast-math`), then ignore the tests `test_cmath test_compile test_complex test_float test_long_future test_math test_strtod`.
3. Else if the flag `-fno-signed-zeros` is enabled (either directly or via `-Ofast`, `-ffast-math`, `-funsafe-math-optimizations`, or `-fno-signed-zeros`), then ignore the tests `test_compile test_complex test_long_future`. (need to retest to see if any other tests should additionally be ignored)
4. Check to see if any of the dependency dynamic libraries were compiled with `-funsafe-math-optimizations` (we can do this by looking in `/var/db/pkg/<package name>/C*FLAGS`), and if so, ignore the tests `test_cmath test_float test_math test_strtod`.

We can also output a warning if any additional tests were ignored so the user is aware that they have a python that doesn't strictly conform to standards.

@InBetweenNames If you guys are fine with this solution I can try to make a pull request. I don't have much experience working with ebuilds so it may take me some time to get up to speed.

**Comment by asaparov** [comment]
One thing I don't understand, however, is that the failing tests only cause the whole emerge to fail for 2.7.15-r108. I just tried emerging python-3.6.6-r1 and 3.7.0-r1 and those finish fine, even though I can see the same tests failing in `build.log`.

**Comment by InBetweenNames** [comment]
It looks good to me!  I don't use `-Ofast` but it would be nice to support such users.

**Comment by asaparov** [comment]
@InBetweenNames So I realize now why the emerge fails for 2.7.15-r108 but not 2.7.15-r1, 3.6.6-r1, or 3.7.0-r1. The ` || true` at the end of https://github.com/InBetweenNames/gentooLTO/blob/master/dev-lang/python/files/python-2.7.15-PGO.patch#L57 was removed. So any failing instrumentation tests cause the whole emerge to fail.

So we have two options: (1) make all python ebuilds require the tests to succeed, and we can implement the above workaround, or (2) add the ` || true` back to the end of that command.

I personally think (2) is better since it seems to be what the python developers intended, and it's also a lot easier for us to maintain.

**Comment by InBetweenNames** [comment]
Could you submit a PR for that?  I agree the || approach is probably best.

**Comment by bicici** [comment]
If Ofast is not implemented / supported, warnings can be added to the code. cpython with test_buffer.py gets frozen / hangs and also later in other unittests in other libraries too if test_buffer.py is past with cancelling the compilation.
