### ISSUE TITLE
I have a Question. (?)

### ISSUE THREAD

**Issue by javashin** [InBetweenNames/gentooLTO#375]
Hello Im Worried About Something I Have Gnome Desktop On Gentoo , And Its Lagging A Lot
On Applications Menu Extension And Every Where In Wayland , Kinda Not Happen On Xorg Session Of Gnome
But I Installed Debian Buster 10 Which Have Same Version Of Gnome 3.30.2 And On Wayland Session Everything Is Fine No Lagging Anywhere Mesa Versions Differ Very Old One 18.X.X  , Also I Installed Arch With Gnome 3.32 And On Wayland Session Using Same Mesa As Gentoo 19.X.X And There Is No Lag Either ,

So My Question Is Does Harder Optimizations Can Hurt Gui EGL OPENGL Wayland Clutter Mutter Gnome-Shell 
and Cause To Not Render Like It Has To be  This Is Really Annoying What Im Doing Wrong , Whats Going On I need To Solve This , Anyone Has Same Issue , The Only Thing Thats is Different For Debian And Arch Is That They Use Sane Cflags So thats Why I ask This Please Leave a Fix In The Comments if there Are Any .  

By Lagging Im Talking About Mouse LAG in Wayland Slowness ETC.

**Comment by jiblime** [comment]
I would try building a whole new system with sane CFLAGS for Gentoo specifically. It could be a problem that is specific to settings or Gentoo for Gnome.

**Comment by InBetweenNames** [comment]
Well, I actually just got Gnome installed myself.  So far, it seems to be working fine for me.  Now I could see whichever flags you are using causing problems here.  I recall you saying that you use `-funroll-loops` and `-mfpmath=both`, which will almost certainly hurt your performance.

Also, Wayland uses software cursors instead of hardware cursors, to my knowledge.  I recall discussions about the lag imposed by hardware cursors in wayland.

A few possibilities.   If you have v-sync on, that'll absolutely impose lag.  Does wayland still force v-sync?  I can't test as I'm on Nvidia.

**Comment by javashin** [comment]
so -funroll-loops and -mfpmath=both are not good for performance , i dont know  ,never have a problem with anything else citra-emu dolphin-emu ppsspp pcsx2 those emulators are heavy opengl consumers and vulkan and are faster than any other distro is just this lagging on gnome in wayland that bothers me , but dont know why wayland on arch and debian works better than gentoo , gnome on xorg is not a problem at all

**Comment by javashin** [comment]
Fixed everything just Upgrading to gnome 3.32 Thanks Aggressive Hard Optimizations Dont have anything to do with this wayland lagging is just bogus gnome 3.30 outdated from gentoo portage
