### ISSUE TITLE
Lacking required gcc USE flags in README

### ISSUE THREAD

**Issue by bakape** [InBetweenNames/gentooLTO#421]
Correct me, if this is just a misconfiguration of my own system, but it seems that applying the `make.conf` changes described in the README without having your active gcc compiled with `lto pgo graphite` (or at least one of these - have not checked combinatorially) results in `C compiler cannot create executables` on any non-gcc emerge attempt. These flag(s) are not mentioned in the README as required.  

Does this requirement make sense and maybe can comebody reproduce on their own system?

**Comment by jiblime** [comment]
The USE flags lto and pgo won't affect what GCC can compile but are supposed to help with runtime performance at the expense of a longer build. You do need graphite for `-fgraphite-identity` and possibly `-floop-nest-optimize`. 

If you've removed those two and you still get an error, it would probably be because you have a minor typo in your CFLAGS. GCC's ebuild strips most flags and would allow you to build "with" something like `CFLAGS="O3 -arch=native -lto"`, same with sys-devel/binutils

**Comment by bakape** [comment]
Sorry, if I wasn't clear enough. Let me more constructively break down my perceived problem:

Steps to reproduce: 
1. Compile GCC 9 (currently 9.2.0-r1) without the `graphite` USE flag.
2. Make sure this GCC is the default compiler with `gcc-config`.
3. emerge any atom that uses GCC for compilation and does not heavily ignore compile flags. Example: `app-misc/screen`. 

Expected behaviour:
Atom compiles.

Actual behavior: 
Atom compilation fails during configure phase with `C compiler cannot create executables`.

What I am asking is:
1. If somebody else can reproduce this, to make sure it is not somehow specific to my configuration.
2. If it is reproducible, should the requirement of the `graphite` USE flag on GCC be either documented, automatically set by gentooLTO or both to prevent unexpected breakage?

**Comment by wolfwood** [comment]
you are correct, it should be documented. i don't think the project should
force graphite-enabled gcc as a dependency, but it is necessary for the
default configuration.

**Comment by jiblime** [comment]
@bakape, I see. That was my mistake, I assumed you had used the flags without installing ltoize. Graphite as a GCC dependency was removed from it recently.

1. Yes, it is reproducible for me. 

2. The dependency is documented in make.conf.lto.defines, so it's not very visible. It would be good if the whole defines file with its descriptions were in the wiki. 

@wolfwood, I think it'd make sense to add something like this to ltoize rather than removing it from the default:
```
RDEPEND="
	graphite? ( sys-devel/gcc[graphite] )
"
```

To give users a choice and remind them to add graphite to their USE flags.
