### ISSUE TITLE
dev-python/libvirt-python-6.1.0 failed to compile with LTO

### ISSUE THREAD

**Issue by alexminder** [InBetweenNames/gentooLTO#497]
Hi,
I found that `dev-python/libvirt-python-6.1.0` doesn't build using the default LTO configuration, it fails during the configure phase:

```
lto1: internal compiler error: resolution sub id 0xa5ab1a963646e5fa not in object file
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.gentoo.org/> for instructions.
lto-wrapper: fatal error: x86_64-pc-linux-gnu-gcc returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
```

I just added the following to ltoworkarounds:
`dev-python/libvirt-python *FLAGS-=-flto*`

**Comment by wolfwood** [comment]
I also have this workaround

**Comment by nivedita76** [comment]
Is this specific to python version or something? I have it built with LTO here.

`dev-python/libvirt-python-6.1.0::gentoo was built with the following:`
`USE="-examples -test" ABI_X86="(64)" PYTHON_TARGETS="python3_6 -python3_7"`
`CFLAGS="-pipe -march=native -O2 -falign-functions=32 -flimit-function-alignment -fno-plt -Wl,-O1 -Wl,--as-needed -O3 -fira-loop-pressure -flive-range-shrinkage -fno-common -fno-math-errno -fno-trapping-math -fipa-pta -flto=32 -mtls-dialect=gnu2"`

**Comment by nivedita76** [comment]
Hm something must have changed recently.. I can't rebuild it, I do get that error.

My successful build was on March 17th.

**Comment by nivedita76** [comment]
gcc and binutils seem to be from before then

**Comment by InBetweenNames** [comment]
I seem to have been able to build it here:

~~~
dev-python/libvirt-python-6.2.0::gentoo was built with the following:
USE="-examples -test" ABI_X86="(64)" PYTHON_TARGETS="python3_7 -python3_6"
CFLAGS="-march=native -falign-functions=32 -malign-data=cacheline -fno-plt -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=12 -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed"
CXXFLAGS="-march=native -falign-functions=32 -malign-data=cacheline -fno-plt -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=12 -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed"
~~~

**Comment by InBetweenNames** [comment]
Could this be an `-fno-common` problem?

**Comment by wolfwood** [comment]
this now builds for me, even not disabling lto

**Comment by InBetweenNames** [comment]
@alexminder are you still encountering this problem?

**Comment by alexminder** [comment]
@InBetweenNames , with `dev-python/libvirt-python-6.2.0` no problem. Thanks for reply!

```
dev-python/libvirt-python-6.2.0::gentoo was built with the following:
CFLAGS="-march=ivybridge -O3 -fno-semantic-interposition -fgraphite-identity -floop-nest-optimize -flto=8 -fuse-linker-plugin -pipe -falign-functions=32 -Wl,-O1 -Wl,--as-needed"
CXXFLAGS="-march=ivybridge -O3 -fno-semantic-interposition -fgraphite-identity -floop-nest-optimize -flto=8 -fuse-linker-plugin -pipe -falign-functions=32 -Wl,-O1 -Wl,--as-needed"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -march=ivybridge -O3 -fno-semantic-interposition -fgraphite-identity -floop-nest-optimize -flto=8 -fuse-linker-plugin -pipe -falign-functions=32"
```

**Comment by Gooberpatrol66** [comment]
I'm encountering this problem.
<log>
 * Package:    dev-python/libvirt-python-6.2.0
 * Repository: gentoo
 * Maintainer: tamiko@gentoo.org virtualization@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python3_7 userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
qlop: invalid option -- 'g'
usage: qlop [opts] <pkgname> : emerge log analyzer

The --date option can take a few forms:
  -d '# <day|week|month|year>[s] [ago]'  (e.g. '3 days ago')
Or using strptime(3) formats:
  -d '2015-12-25'           (detected as %Y-%m-%d)
  -d '1459101740'           (detected as %s)
  -d '%d.%m.%Y|25.12.2015'  (format is specified)

options: -[ctaHMmuUsElerd:f:w:F:vqChV]
  -c, --summary       * Print summary of average merges (implies -a)
  -t, --time          * Print time taken to complete action
  -a, --average       * Print average time taken to complete action
  -H, --human         * Print elapsed time in human readable format (use with -t or -a)
  -M, --machine       * Print start/elapsed time as seconds with no formatting
  -m, --merge         * Show merge history
  -u, --unmerge       * Show unmerge history
  -U, --autoclean     * Show autoclean unmerge history
  -s, --sync          * Show sync history
  -E, --emerge        * Show last merge similar to how emerge(1) -v would show it
  -e, --endtime       * Report time at which the operation finished (iso started)
  -r, --running       * Show current emerging packages
  -d, --date <arg>    * Limit selection to this time (1st -d is start, 2nd -d is end)
  -l, --lastmerge     * Limit selection to last Portage emerge action
  -f, --logfile <arg> * Read emerge logfile instead of $EMERGE_LOG_DIR/emerge.log
  -w, --atoms <arg>   * Read package atoms to report from file
  -F, --format <arg>  * Print matched atom using given format string
      --root <arg>    * Set the ROOT env var
  -v, --verbose       * Report full package versions, emit more elaborate output
  -q, --quiet         * Tighter output; suppress warnings
  -C, --nocolor       * Don't output color
  -h, --help          * Print this help and exit
  -V, --version       * Print version and exit
2018-10-18T19:10:45 >>> dev-python/libvirt-python: 52 seconds
2019-01-08T23:06:11 >>> dev-python/libvirt-python: 58 seconds
2019-04-02T04:56:40 >>> dev-python/libvirt-python: 1 minute, 20 seconds
2019-05-10T07:50:24 >>> dev-python/libvirt-python: 1 minute, 5 seconds
2019-08-13T02:39:19 >>> dev-python/libvirt-python: 35 seconds
2020-01-04T18:10:02 >>> dev-python/libvirt-python: 47 seconds
2020-03-02T01:23:07 >>> dev-python/libvirt-python: 29 seconds
2020-04-02T22:04:40 >>> dev-python/libvirt-python: 51 seconds
/etc/portage/bashrc.d/10-title.sh: line 24: 2018-10-18T19: value too great for base (error token is "18T19")
 * /etc/portage/package.cflags/ltoworkarounds.conf -> dev-python/libvirt-python: *FLAGS-="${IPAPTA}" # Test failure
 * FEATURES='ebuild-locks news protect-owned unknown-features-warn userfetch fixlafiles sandbox preserve-libs distlocks xattr config-protect-if-modified userpriv usersync multilib-strict qa-unresolved-soname-deps assume-digests unmerge-orphans usersandbox binpkg-logs parallel-fetch sfperms ipc-sandbox merge-sync binpkg-docompress strict unmerge-logs network-sandbox pid-sandbox binpkg-dostrip'
 * CFLAGS='-march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu'
 * CXXFLAGS='-march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu'
 * FFLAGS='-march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu'
 * FCFLAGS='-march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu'
 * F77FLAGS='-march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu'
 * LDFLAGS='-Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin'
 * MAKEOPTS='-j4'
 * gcc (Gentoo 9.2.0-r2 p3) 9.2.0
 * Linux gentoodesktop 5.6.4-gentoo #6 SMP PREEMPT Tue Jun 2 16:23:22 CDT 2020 x86_64 AMD Ryzen 5 1600 Six-Core Processor AuthenticAMD GNU/Linux
>>> Unpacking source...
>>> Unpacking libvirt-python-6.2.0.tar.gz to /var/tmp/portage/dev-python/libvirt-python-6.2.0/work
>>> Source unpacked in /var/tmp/portage/dev-python/libvirt-python-6.2.0/work
!!! Repository 'Drauthius' has sync-type attribute set to unsupported value: 'laymansync'
!!! Installed sync-types are: '['cvs', 'git', 'rsync', 'svn', 'webrsync']'
!!! Repository 'aeon-gentoo-overlay' has sync-type attribute set to unsupported value: 'laymansync'
!!! Installed sync-types are: '['cvs', 'git', 'rsync', 'svn', 'webrsync']'
!!! Repository 'guru' has sync-type attribute set to unsupported value: 'laymansync'
!!! Installed sync-types are: '['cvs', 'git', 'rsync', 'svn', 'webrsync']'
!!! Repository 'lmiphay' has sync-type attribute set to unsupported value: 'laymansync'
!!! Installed sync-types are: '['cvs', 'git', 'rsync', 'svn', 'webrsync']'
!!! Repository 'nix-guix' has sync-type attribute set to unsupported value: 'laymansync'
!!! Installed sync-types are: '['cvs', 'git', 'rsync', 'svn', 'webrsync']'
!!! Repository 'pentoo' has sync-type attribute set to unsupported value: 'laymansync'
!!! Installed sync-types are: '['cvs', 'git', 'rsync', 'svn', 'webrsync']'
!!! Repository 'snapd' has sync-type attribute set to unsupported value: 'laymansync'
!!! Installed sync-types are: '['cvs', 'git', 'rsync', 'svn', 'webrsync']'
>>> Preparing source in /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0 ...
 * python3_7: running distutils-r1_run_phase distutils-r1_python_compile
 * DISTUTILS_USE_SETUPTOOLS value is probably incorrect
 *   value:    DISTUTILS_USE_SETUPTOOLS=bdepend (default?)
 *   expected: DISTUTILS_USE_SETUPTOOLS=no
python3.7 setup.py build -j 4
running build
/usr/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
/usr/bin/python3.7 generator.py libvirt /usr/share/libvirt/api/libvirt-api.xml
Found 478 functions in /usr/share/libvirt/api/libvirt-api.xml
Found 0 functions in libvirt-override-api.xml
Generated 389 wrapper functions
/usr/bin/python3.7 generator.py libvirt-qemu /usr/share/libvirt/api/libvirt-qemu-api.xml
Found 5 functions in /usr/share/libvirt/api/libvirt-qemu-api.xml
Found 0 functions in libvirt-qemu-override-api.xml
Generated 3 wrapper functions
/usr/bin/pkg-config --atleast-version=1.0.2 libvirt
/usr/bin/python3.7 generator.py libvirt-lxc /usr/share/libvirt/api/libvirt-lxc-api.xml
Found 4 functions in /usr/share/libvirt/api/libvirt-lxc-api.xml
Found 0 functions in libvirt-lxc-override-api.xml
Generated 2 wrapper functions
running build_py
copying build/libvirt.py -> /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/lib
copying build/libvirt_qemu.py -> /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/lib
copying build/libvirt_lxc.py -> /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/lib
copying build/libvirtaio.py -> /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/lib
warning: build_py: byte-compiling is disabled, skipping.

running build_ext
building 'libvirtmod' extension
building 'libvirtmod_qemu' extension
building 'libvirtmod_lxc' extension
creating /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7
creating /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7
creating /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7
creating /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/build
creating /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/build
creating /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/build
x86_64-pc-linux-gnu-gcc -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -fPIC -I. -I/usr/include/python3.7m -c libvirt-qemu-override.c -o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/libvirt-qemu-override.o
x86_64-pc-linux-gnu-gcc -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -fPIC -I. -I/usr/include/python3.7m -c libvirt-lxc-override.c -o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/libvirt-lxc-override.o
x86_64-pc-linux-gnu-gcc -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -fPIC -I. -I/usr/include/python3.7m -c libvirt-override.c -o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/libvirt-override.o
x86_64-pc-linux-gnu-gcc -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -fPIC -I. -I/usr/include/python3.7m -c build/libvirt-qemu.c -o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/build/libvirt-qemu.o
x86_64-pc-linux-gnu-gcc -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -fPIC -I. -I/usr/include/python3.7m -c build/libvirt-lxc.c -o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/build/libvirt-lxc.o
x86_64-pc-linux-gnu-gcc -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -fPIC -I. -I/usr/include/python3.7m -c typewrappers.c -o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/typewrappers.o
x86_64-pc-linux-gnu-gcc -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -fPIC -I. -I/usr/include/python3.7m -c typewrappers.c -o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/typewrappers.o
x86_64-pc-linux-gnu-gcc -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -fPIC -I. -I/usr/include/python3.7m -c libvirt-utils.c -o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/libvirt-utils.o
x86_64-pc-linux-gnu-gcc -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -fPIC -I. -I/usr/include/python3.7m -c libvirt-utils.c -o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/libvirt-utils.o
x86_64-pc-linux-gnu-gcc -shared -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/libvirt-qemu-override.o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/build/libvirt-qemu.o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/typewrappers.o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/libvirt-utils.o -L/usr/lib64 -lvirt-qemu -lpython3.7m -o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/lib/libvirtmod_qemu.cpython-37m-x86_64-linux-gnu.so
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/libvirt-utils.o: file not recognized: file truncated
collect2: error: ld returned 1 exit status
x86_64-pc-linux-gnu-gcc -shared -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/libvirt-lxc-override.o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/build/libvirt-lxc.o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/typewrappers.o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/libvirt-utils.o -L/usr/lib64 -lvirt-lxc -lpython3.7m -o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/lib/libvirtmod_lxc.cpython-37m-x86_64-linux-gnu.so
x86_64-pc-linux-gnu-gcc -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -fPIC -I. -I/usr/include/python3.7m -c build/libvirt.c -o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/build/libvirt.o
x86_64-pc-linux-gnu-gcc -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -fPIC -I. -I/usr/include/python3.7m -c typewrappers.c -o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/typewrappers.o
x86_64-pc-linux-gnu-gcc -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -fPIC -I. -I/usr/include/python3.7m -c libvirt-utils.c -o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/libvirt-utils.o
x86_64-pc-linux-gnu-gcc -shared -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fno-semantic-interposition -flto=12 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/libvirt-override.o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/build/libvirt.o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/typewrappers.o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/temp.linux-x86_64-3.7/libvirt-utils.o -L/usr/lib64 -lvirt -lpython3.7m -o /var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0-python3_7/lib/libvirtmod.cpython-37m-x86_64-linux-gnu.so
error: command 'x86_64-pc-linux-gnu-gcc' failed with exit status 1
 * ERROR: dev-python/libvirt-python-6.2.0::gentoo failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  125:  Called src_compile
 *   environment, line 4072:  Called distutils-r1_src_compile
 *   environment, line 2365:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_compile'
 *   environment, line 1624:  Called python_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 3695:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 3201:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 3199:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2007:  Called distutils-r1_run_phase 'distutils-r1_python_compile'
 *   environment, line 2356:  Called distutils-r1_python_compile
 *   environment, line 2226:  Called esetup.py 'build' '-j' '4'
 *   environment, line 2745:  Called die
 * The specific snippet of code:
 *       "${@}" || die "${die_args[@]}";
 * 
 * If you need support, post the output of `emerge --info '=dev-python/libvirt-python-6.2.0::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-python/libvirt-python-6.2.0::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/dev-python/libvirt-python-6.2.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-python/libvirt-python-6.2.0/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0'
 * S: '/var/tmp/portage/dev-python/libvirt-python-6.2.0/work/libvirt-python-6.2.0'
</log>
