### ISSUE TITLE
media-gfx/imagemagick-7.0.10.9:0/7.0.10::gentoo - doesn't build with LTO

### ISSUE THREAD

**Issue by leandrolnh** [InBetweenNames/gentooLTO#525]
I've got a couple of these error in the log:

`libtool: link: /usr/bin/x86_64-pc-linux-gnu-nm -B  coders/.libs/dcm_la-dcm.o   |  | /bin/sed 's/.* //' | sort | uniq > coders/.libs/dcm.exp`
`./libtool: eval: line 1744: syntax error near unexpected token '|'`
`./libtool: eval: line 1744: '/usr/bin/x86_64-pc-linux-gnu-nm -B  coders/.libs/dcm_la-dcm.o   |  | /bin/sed 's/.* //' | sort | uniq > coders/.libs/dcm.exp'`
`make[1]: *** [Makefile:7098: coders/dcm.la] Error 2`

Removing LTO solves the issue:
`media-gfx/imagemagick *FLAGS-="${FLTO}"`

**Comment by elsandosgrande** [comment]
I believe that that error is a result of combining the GCC 10 default of `-fno-common` with `-flto`. Since I have been away due to _reasons_ and cannot yet insert my old laptop's Gentoo HDD into my new laptop because of a few stubborn screws, I am not in a position to double-check that. 

By the way, this post of mine might clue you in on a portion of the _reasons_: https://forums.gentoo.org/viewtopic.php?p=8420646

**Comment by leandrolnh** [comment]
Swapping `*FLAGS-="${FLTO}"` with `*FLAGS="-fcommon"` also solves the issue.

What is better: remove LTO or restore `-fcommon`?

**Comment by elsandosgrande** [comment]
It's better to restore `-fcommon`.
1. If you have to choose one over the other, I would wager that link-time optimization has a higher impact on average.
2. Isn't this overlay called Gentoo**LTO**? It would be ideal to maintain link-time optimization wherever possible.

Also, [nivedita76's reply in one of the pull requests](https://github.com/InBetweenNames/gentooLTO/pull/290#issuecomment-582168591) kind of addresses this kind of issue and is something to keep in mind.

**Comment by leandrolnh** [comment]
Well, it looks like the following seems to solve the issue without workarounds:
https://github.com/InBetweenNames/gentooLTO/issues/514#issuecomment-626367452

Closing this.
