### ISSUE TITLE
README should mention linker plugin symlink

### ISSUE THREAD

**Issue by rx80** [InBetweenNames/gentooLTO#6]
For LTO to work properly
`/usr/x86_64-pc-linux-gnu/binutils-bin/lib/bfd-plugins/liblto_plugin.so`
has to point to the current active version of gcc, e.g. :
`/usr/libexec/gcc/x86_64-pc-linux-gnu/7.2.0/liblto_plugin.so`

To fix or make sure the link is correct:
`ln -sf /usr/libexec/gcc/x86_64-pc-linux-gnu/7.2.0/liblto_plugin.so /usr/x86_64-pc-linux-gnu/binutils-bin/lib/bfd-plugins/`

**Comment by InBetweenNames** [comment]
Fixed, thanks!

**Comment by pchome** [comment]
It's dirty hack for _bad_ packages w/ hardcoded ar/nm/ranlib/...
also w/ this hack you probably can ignore/remove corresponding  AR/NM/... variables in/from make.conf
binutils than automatically will load LTO plug-in

you may not recommend this if you want this packages to be fixed 
or this behaviour must be controlled by eselect/gcc-config somehow

fyi: I just found broken symlink in bfd-plugins/ directory pointing to one early gcc version 5  ;-)

**Comment by InBetweenNames** [comment]
@pchome Thanks--time limited tonight but I'll look into that tomorrow.  I think I'll remove the symlink from `ltoize` or perhaps just document it in the readme.  It would be nice to have something I could cite for future reference however.  I have noticed that on my own system, the symlink is not needed.

**Comment by pchome** [comment]
https://marxin.github.io/posts/gentoo-linux-packages-with-gcc-4-dot-9-lto/#installation
https://sourceware.org/ml/binutils/2014-01/msg00213.html

gcc-ar/gcc-nm/gcc-ranlib wrappers is ok till every package respects AR/NM/RANLIB variables
but sometimes ar/nm/ranlib called directly and no plugin loaded then
you can detect this behaviour by searching for "plugin needed to handle lto object" messages in build output

> Binutils already has the ability to load plugins from the lib/bfd-plugins directory

this trick w/ symlink adds plugin which binutils can use and ar/nm/ranlib then have option `--plugin`
you can check `ranlib --help | grep "\-\-plugin"` for example, w/ symlink you'll see  `--plugin <name>              Load the specified plugin`

> I have noticed that on my own system, the symlink is not needed.

most packages builds despite  "no plugin" warnings, not sure if it's good or bad
maybe we lose some important lto benefits
like `strip` problem: https://sourceware.org/bugzilla/show_bug.cgi?id=21479

**Comment by InBetweenNames** [comment]
The `strip` thing is something I have noticed as well.  It seemed to be a known problem, but I can't remember offhand which mailing lists I saw people discussing it.  Thanks for bringing this up!

Just to reiterate to make sure I understand: it seems that if a package behaves properly, it should source the `AR`, `NM`, and `RANLIB` commands directly from those environment variables, which would resolve to `gcc-ar`, `gcc-nm`, and `gcc-ranlib`, respectively, in our config here.  I suspect eventually we'll have a `STRIP` variable as well.  However, if the package is not well written--it just invokes `ar`, `nm`, and `ranlib` directly.  Perhaps this is something out of the ebuild's hands, like a lower level problem that would require an upstream patch to fix.  I expect those packages to also have problems with crossdev as well.

I don't actually expect us to lose out on much with `strip` not handling LTO yet--the biggest difference would be binary size.

With binutils now handling automatic LTO plugin loading from the `bfd-plugins` directory, I'm wondering now what is the preferred method to handle LTO?  In either case, we should be running into the `strip` problem, the only difference is that the wrappers directly do the `--plugin` for us.  I find it curious that such a patch would be merged into binutils if the wrappers were supposed to be used instead--or perhaps those are a holdover from previous binutils that didn't automatically load it?  Myself, I'm leaning towards removing the symlink and leaving a note in the README since it seems to me that `AR`, `NM`, and `RANLIB` should be respected for crossdev purposes alone.  Your thoughts?

I could put together a `gcc-config` patch as well to create the symlink.  I'm glad we're revising this to nail down a standard configuration for LTO.

**Comment by InBetweenNames** [comment]
I messed around with GCC to get it to build with -O3, Graphite, and LTO.  Interestingly, it does not seem to honour AR, NM, and RANLIB.  It wants x86_64-pc-linux-gnu-ar, x86_64-pc-linux-gnu-nm, and x86_64-pc-linux-gnu-ranlib on my system.  Probably because of the host/build/target separation, which is required for cross compilation.  On a native build it just looks for the ${CHOST}-{ar/nm/ranlib/strip} in the second stage.  This actually has me leaning more in the direction of patching `gcc-config` to install the linker plugin now rather than setting AR, NM, and RANLIB ourselves.  Interestingly, `gcc-config` has not been updated since August 2015.  I'm wondering if there are other edge cases we weren't aware of as well.

I'll ping the maintainer of `gcc-config` to see what they would think about this change and possibly send a PR.

**Comment by pchome** [comment]
https://bugs.gentoo.org/630066

**Comment by InBetweenNames** [comment]
Just wrote a patch.  I will attach it to that bug report.

**Comment by InBetweenNames** [comment]
Patch is here: https://bugs.gentoo.org/630066#c1

I can integrate this into the repo if people are interested.  If this gets accepted, we can go forth with the automatic linker plugin approach and remove AR, NM, and RANLIB.
