### ISSUE TITLE
Patch does not take effect when building app-arch/zstd-1.4.8-r1

### ISSUE THREAD

**Issue by SaltyKitkat** [InBetweenNames/gentooLTO#676]
I modified the patch to fit `zstd-1.4.8-r1`, and put the patch file under the portage repo tree:
```
$ ls /var/db/repos/lto-overlay/sys-config/ltoize/files/patches/app-arch/zstd-1.4.8
zstd-1.4.8-multi-thread-default.patch
```
After rebuild the zstd package, `zstd` is not modified at all.
The `build.log` shows that the sources code is copied from 
`/var/tmp/portage/app-arch/zstd-1.4.8-r1/work/zstd-1.4.8`
to
`/var/tmp/portage/app-arch/zstd-1.4.8-r1/work/zstd-1.4.8-abi_x86_64.amd64`
before  the patch is applied,which means the source code in `zstd-1.4.8-abi_x86_64.amd64` is not patched.
Is this an expected behavior?

**Comment by chaoskagami** [comment]
I just ran into this. I'm looking at this patch and what does it even have to do with the purpose of this repo?

It changes the default behavior from single threaded mode to multi-threaded, and in my opinion that's not even desirable behavior since it adds extra CPU load and worsens compression. Unlike the rest of the ltoize patches, it's not fixing compilation failures.

IMO This has no place in the ltoize patchset. This is something to put in `/etc/portage/patches` if you want it, but it shouldn't be here.

**Comment by InBetweenNames** [comment]
Yeah on further investigation, it looks like initially this patch was to integrate Clear Linux's patchset into GentooLTO for this package, which actually enabled multithreading by default.  This was in commit 579ed2dacb39cebe409dd14a4eb573e6a8de1e1b.  Many users have been wanting Clear Linux patchsets to be integrated in with GentooLTO, so I was quite receptive to this.

However, I agree this is out of scope, especially considering that this isn't a tradeoff everyone will be happy with.  As of such, I'm going to remove the patch from the repository for the time being -- not that I'm forgetting about it by any means.  As part of my goal for 2021 to make GentooLTO more modular, I'd like to reintroduce support for this patchset, and other Clear Linux patchsets, in an "opt-in" way for users that are interested in them.  Then people can decide individually if this system-wide default makes sense for them.
