### ISSUE TITLE
GCC 11 is now in ~arch

### ISSUE THREAD

**Issue by EmRowlands** [InBetweenNames/gentooLTO#736]
As of commit [cc068d96fb49e308456cbe944fb29b1f78e6ad5c](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=cc068d96fb49e308456cbe944fb29b1f78e6ad5c), `sys-devel/gcc-11.1.0` is now in ~arch. Is there anything that needs to be done from the lto-overlay's perspective to support gcc 11? From the looks of the announcement email it doesn't seem like it.

https://archives.gentoo.org/gentoo-dev/message/979b6b8621a210e45bdbf5021cde9dba

**Comment by InBetweenNames** [comment]
Testing it out now!

**Comment by EmRowlands** [comment]
See also:

https://bugs.gentoo.org/show_bug.cgi?id=gcc-11

**Comment by petronio** [comment]
I had to disable LTO on 11.1.0 for it to build, I'll see if fat-lto helps later. Rebuilding world right now to see if there's new failures.

On an unrelated note, if anyone has issues with gnome-session crashing on boot, mask >=gnome-base/gnome-settings-daemon-40 . Still investigating that one, but unrelated to GCC upgrade.

**Comment by InBetweenNames** [comment]
Also had to disable LTO on 11.1.0 to get it to build.  Want to get that sorted out before we make it default.

**Comment by petronio** [comment]
I've got everything more or less building with 11.1.0 , but be prepared to manually bump packages until they make it into ~arch.

Some that I've had to bump in the meantime:
meson to 0.57.2 (this resolves errors in several packages)
srt to 1.4.3
vte to 0.64.0

I think there were some issues with some Gnome packages as well, but I unmasked everything related to v40 and it's all working surprisingly well after the meson bump.

Waiting on a patch for veracrypt and I'm trying to figure out why firefox 88.0-r1 seems to stall mid build.

**Comment by AnonymousRetard** [comment]
I have successfully built GCC 11.1.0 on two gentoo computers with LTO. On the weaker system it failed with normal settings but when I thread again with MAKEOPTS="-j1" and NTHREADS="1" it took a really long time but worked. On the stronger system I lowered NTHREADS from my default 16 down to 8 before even trying and it completed successfully in ~30 minutes with -j32. (AMD 5950).

Could it perhaps be that you guys don't have enough RAM? (Unfortunately I wasn't monitoring the builds so I'm not sure how much it used, but I know this is commonly the issue when trying to build big packages with many LTO threads).

**Comment by ToddAWalter** [comment]
I successfully emerged it with NTHREADS=24 on my 3900x (64GB).  My poor old laptop is still going; it's Skylake with only 16GB so we'll know soon if it's memory starvation.

**Comment by petronio** [comment]
Definitely not memory starvation on my end, tried again and never crossed over 30% usage. I'll try toggling some other things and get back to you guys.

**Comment by InBetweenNames** [comment]
So, turns out the GCC 11 ebuild supports `custom-cflags`.  Previously, we disabled our `flag-o-matic.eclass` overriding behaviour specifically for GCC to ensure that these problematic flags would get stripped out and we'd (mostly) default to Gentoo defaults, throwing in PGO and LTO using `USE=lto pgo` (handled by `toolchain.eclass` itself).

If you have `custom-cflags` enabled for `sys-devel/gcc` somehow (say, a system-wide enable as I'm sure many here use),
that means it'll get picked up when you build GCC 11, and this that means the flags won't get stripped.

So what happens after this is a problem in the bootstrapping phase, it seems.  Because `-flto*` is now present in
`BOOT_CFLAGS`, it's used to build the early stage compilers.  As we know, symbol versioning in static archives
and LTO can't really be used together.  So, this creates a linker error early in the build process.

There's two ways forward:
  - Disable `custom-cflags` for `sys-devel/gcc`, to get back the original behaviour (safer, and you still get LTO and PGO in the final binary)
  - Use `custom-cflags`, but remove `-flto*` from CFLAGS (keeping `USE=lto` to actually use it when it matters)

I'm in favour of the first approach and it's what I'll be recommending, but at least users have some more fine grained control with the second approach if you wanted to go crazy.

I'll make sure to include this info in the GCC 11 announcement for GentooLTO.

**Comment by aqxa1** [comment]
I'm getting GPU hangs with mesa-git (and 21.1.0_rc2) compiled with gcc-11.1.0,
RADV, RX 6800. This applies to a least Portal 1 and 2 (both with DXVK) although not vkcube. Either reverting to GCC 10.3.0, or bypassing the LTO overlay flags to use conservative flags (-march=znver2 -O2 -pipe) works around the issue.

**Comment by King-Mucus** [comment]
I successfully reemerged world after migrating to GCC 11, and had no need to disable custom-cflags or remove -flto* from CFLAGS. I hope it doesn't cause runtime errors on generated binaries. Alas, I'm using Gentoo hardened profile here.

However, I had some issues with some packages.

Firefox compiles fine, but I had to remove -fdevirtualize-at-ltrans for the generated binary to not segfault. Funnily enough, I was unable to compile Librewolf with the very same configuration.

I compiled FF 88.0-r1 and tried compiling Librewolf 88.0.

I was only able to compile nodejs and dav1d after removing -flto* *CFLAG. Haven't tried removing any other compilation flag before that, though.

I'm still unable to compile rxvt-unicode and telegram-desktop here, but it is a known issue related to GCC 11 (and not GentooLTO) and has been reported to bugs.gentoo.org already.

I was also unable to compile gstreamermm here. Because it is only a dependency of a package I hadn't considered very important, I haven't tried revoking any *CFLAG and recompiling it.

**Comment by s0me0ne-coder** [comment]
thanks for the dav1d solution

**Comment by King-Mucus** [comment]
I would like to just point out that, unlike stated previously, I hadn't actually compiled GCC with the custom-cflags USE flag enabled.

After checking those flags, I remembered I had decided to enable it on a per package basis because only a handful of them had this flag enabled.

**Comment by King-Mucus** [comment]
I would like to just point out that, unlike stated previously, I hadn't actually compiled GCC with the custom-cflags USE flag enabled.

After checking those flags, I remembered I had decided to enable it on a per package basis because only a handful of them had this flag enabled.

**Comment by shelterx** [comment]
Seems like dev-db/mysql won't compile at all with  gcc 11. even if i disable lto.

**Comment by ToddAWalter** [comment]
I get an internal compiler error on alembic_read.cpp when building Blender-git.  

`static constexpr TypeDesc type_desc = TypeFloat;` was known to cause this in GCC 6.4, oddly enough.  I don't know if we're too far off the beaten path to file a bug upstream or not.

**Comment by shelterx** [comment]
git suddenly broke for me, i had compile it without LTO to get it to work again.

**Comment by EmRowlands** [comment]
Closing, since GCC11 is now in full use

(a bit late though)

**Comment by halo-shit** [comment]
```internal compiler error: Segmentation fault. ```
I got 12GB mem. lack of mem? 😅
