### ISSUE TITLE
dev-tcltk/tdom fails to build with lto

### ISSUE THREAD

**Issue by leg7** [InBetweenNames/gentooLTO#815]
emake fails

[build.log](https://github.com/InBetweenNames/gentooLTO/files/7698906/build.log)

Gentoo mostly "stable" (not ~) system up to date

**Comment by wolfwood** [comment]
`/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../lib64/libtclstub8.6.a
generated with LTO version 11.0 instead of the expected 11.2`

you have at least one static library that hasn't been rebuilt since you
upgraded gcc.

you can (install and) run `lto-rebuild -r` to find all packages that need
to be rebuilt and emerge them.

if you have equery (from gentoolkit) installed
`equery b
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../lib64/libtclstub8.6.a`
will find which package this specific library *b*elongs to if you are in a
hurry.  or you could take a guess that it's probably `tcl` and rebuild
that.

however `lto-rebuild`, or more conservatively `emerge -eav @world`, is
needed after gcc version change.

**Comment by leg7** [comment]
> 

So I should rebuild my whole system on every gcc update?

**Comment by wolfwood** [comment]
`lto-rebuild` will identify only affected packages (built with lto enabled and installed static libraries, I believe), and that should be sufficient.  that will address build failures due to lto.

 in the past, there have been (non lto related) issues going between major versions of gcc, and other build infrastructure like binutils and glibc.  if you have the time and resources, a global rebuilt when switching to the latest gcc and binutils with `eselect` isn't a bad idea, but it's not strictly necessary, and not recommended by this project as far as i can tell.  maybe more of a defensive habit.

**Comment by wolfwood** [comment]
https://wiki.gentoo.org/wiki/Upgrading_GCC

looks like gcc fixed it's ABI handling a while back so world rebuild are no longer necessary.

**Comment by leg7** [comment]
So I rebuilt my whole system and now it compiles correctly, I will use lto-rebuild on my laptop. Thank you!
