### ISSUE TITLE
Should I Globally Enable LTO and Graphite Use Flags?

### ISSUE THREAD

**Issue by Amarakon55** [InBetweenNames/gentooLTO#818]
So right now my make.conf looks like this:
`# Main
#NTHREADS="4"
#source /etc/portage/make.conf.lto

COMMON_FLAGS="-march=native -O2 -pipe"
#CFLAGS="${COMMON_FLAGS}"
CFLAGS="-march=native ${CFLAGS} -pipe -falign-functions=32"
#CXXFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

MAKEOPTS="-j4 -l8"
EMERGE_DEFAULT_OPTS="-j4 -l8 -tv --autounmask-write --keep-going=y --ask=n"
PORTAGE_NICENESS="1"
FEATURES="ccache parallel-install buildpkg"
CCACHE_DIR="/var/cache/ccache"
RUSTC_WRAPPER=/usr/bin/sccache
SCCACHE_DIR=/var/cache/sccache
SCCACHE_MAX_FRAME_LENGTH=104857600
BINPKG_COMPRESS="lz4"
ACCEPT_KEYWORDS="~amd64"
ACCEPT_LICENSE="-* @FREE"
VIDEO_CARDS="intel i915"
INPUT_DEVICES="libinput"
USE="-firmware -xinerama alsa -jack -pipewire -pulseaudio savedconfig \
     jemalloc pgo -clang -introspection -systemd -gnome -kde -ios \
     -ipod -emacs -xemacs -ipv6 -bluetooth -gstreamer -vorbis \
     zsh-completion -geolocation -libnotify -doc -tiff -joystick \
     -gmp-autoupdate -handbook -cxx -aqua -css -a52 -qt4 -ldap -3df \
     -berkdb -clamav -coreaudio -ie1394 -gtk -motif -emboss -3dfx \
     -altivec -smartcard -ibm -nas -neon -nntp threads elogind X lz4 \
     -gtk-doc -vala -zstd"

# NOTE: This stage was built with the bindist Use flag enabled
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C
L10N=en-CA

# Other
GRUB_PLATFORMS="pc"
GENTOO_MIRRORS="http://gentoo.gossamerhost.com http://gentoo.mirros.tera-byte.com/ https://mirror.csclub.uwaterloo.ca/gentoo-distfiles/ https://gentoo.osuosl.org/ https://mirrors.rit.edu/gentoo/"`

I have the LTO and Graphite optimizations, but I haven't enabled the LTO and Graphite use flags. I only enabled the graphite use flag for GCC because it was necessary. I'm a bit confused here. Should I enable the LTO and Graphite use flags globally or not?

**Comment by jiblime** [comment]
```
#NTHREADS="4"
#source /etc/portage/make.conf.lto
```

You need to uncomment those so the CFLAGS variable from make.conf.lto is sourced and expanded in ` CFLAGS="-march=native ${CFLAGS} -pipe -falign-functions=32"`

LTO support is built with GCC by default on Gentoo. You are correct that you needed to enable the graphite USE flag. 

You have GCC's optimization flags and Gentoo's use flags mixed up. `-flto`, `-fgraphite-identity`, `fno-semantic-interposition`; those are optimization flags that your compiler uses. When placed in your *FLAGS variables, they will be automatically used on every package except those with workarounds found by the community, by Gentoo's own system (`strip-flags` function in the flag-o-matic.eclass) because people like me don't know any better, or yourself.

There are a few packages that explicitly enable/disable LTO because different parts of the source can or can't be built with LTO. The lto USE flag in sys-devel/gcc is one of those cases.

**Comment by Amarakon55** [comment]
So this LTO is optimization flags, not use flags, got it. I uncommented those lines as I did not realize they were even commented. I recompiled packages using lto-rebuild and everything works great. I know that I must have graphite use flag enabled for GCC. But should I enable graphite and LTO use flags globally? What does the LTO use flag do if I already built all my packages with LTO optimizations?

Also, last question: I have a certain package that fails with these optimizations. How do I force it to use the common flags instead of my cflags?

**Comment by jiblime** [comment]
> But should I enable graphite and LTO use flags globally?

No to graphite; there is at most 5 packages that have that flag, and one of them, `media-libs/harfbuzz`, uses the graphite USE flag for text rendering.

For the lto USE flag, that's a personal choice. I use it per package instead of globally. When there is an LTO flag, that typically means that package is a pain in the butt to build and can take significantly longer or is prone to failing to compile. An example is `net-libs/nodejs`. That doubles in compile time for me with the LTO flag.

> What does the LTO use flag do if I already built all my packages with LTO optimizations?

It builds GCC itself with LTO, to make the installed gcc package smaller in size and possibly faster for compiling. 

> Also, last question: I have a certain package that fails with these optimizations. How do I force it to use the common flags instead of my cflags?

Two options that I can think of:

https://wiki.gentoo.org/wiki//etc/portage/package.env

and

https://github.com/InBetweenNames/gentooLTO#how-to-use-this-configuration

`/etc/portage/bashrc.d/README` from `app-portage/portage-bashrc-mv`, really great tool that is required with this overlay

**Comment by Amarakon55** [comment]
Okay, I enabled LTO use flag globally but disabled graphite globally and is only used for GCC. When I tried to compile nodejs with this use flag, it complained saying it was unsupported so I disabled it only for nodejs. I will use package.env to make the certain package use common flags instead of cflags. Thanks, I'm closing this issue as it is solved.
