### ISSUE TITLE
dev-libs/isl  compiling fail

### ISSUE THREAD

**Issue by antonellocaroli** [InBetweenNames/gentooLTO#830]
My fail....

**Comment by wolfwood** [comment]
you need to remove the graphite-related options from your CFLAGS first,
otherwise compiles will fail because the compiler doesn't support graphite
yet.

try this for a quick fix
CFLAGS="-O2 -march=native -pipe" USE="-lto -pgo graphite" emerge -av gcc

then do the real build (assuming graphite is now in your use flags, along
with lto and pgo)
emerge -av gcc
